# GENERATED FROM contract/openapi.yaml — DO NOT EDIT.
# Regenerate with datamodel-code-generator==0.76.0 (full flags: scripts/generate.sh in dtugm/naraga-contract)
# ruff: noqa
# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field, RootModel


class Timestamp(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(
        ...,
        description="RFC3339 UTC. Producers MUST serialize with millisecond precision and a literal\n`Z` (e.g. 2026-09-01T03:00:00.000Z) — Python's default isoformat() emits\nmicroseconds and no Z, JS toISOString() emits milliseconds and Z. Timezone-naive\nvalues are rejected. Consumers MUST accept any valid RFC3339 instant.\n(No regex `pattern` here on purpose: with format=date-time, generators emit a\nreal datetime type and a string pattern cannot be applied to it.)\n",
        examples=['2026-09-01T03:00:00.000Z'],
    )


class BboxItem(RootModel[float]):
    root: float = Field(..., description='min_lon', ge=-180.0, le=180.0)


class BboxItem1(RootModel[float]):
    root: float = Field(..., description='min_lat', ge=-90.0, le=90.0)


class BboxItem2(RootModel[float]):
    root: float = Field(..., description='max_lon', ge=-180.0, le=180.0)


class BboxItem3(RootModel[float]):
    root: float = Field(..., description='max_lat', ge=-90.0, le=90.0)


class Bbox(RootModel[tuple[BboxItem, BboxItem1, BboxItem2, BboxItem3]]):
    """
    ALWAYS EPSG:4326 decimal degrees, regardless of the dataset's `crs`.
    Antimeridian-crossing extents are expressed with min_lon > max_lon.

    """

    root: tuple[BboxItem, BboxItem1, BboxItem2, BboxItem3] = Field(
        ...,
        description="ALWAYS EPSG:4326 decimal degrees, regardless of the dataset's `crs`.\nAntimeridian-crossing extents are expressed with min_lon > max_lon.\n",
        examples=[[110.36, -7.82, 110.42, -7.78]],
    )


class Crs(RootModel[str]):
    root: str = Field(
        ...,
        description='Authority:code form only. Not WKT, not a bare integer.',
        examples=['EPSG:4326', 'EPSG:32749'],
        pattern='^EPSG:[0-9]{4,6}$',
    )


class ServiceName(StrEnum):
    building_extraction = 'building_extraction'
    pointcloud_classification = 'pointcloud_classification'
    landcover_detection = 'landcover_detection'
    reconstruction_3d = 'reconstruction_3d'
    converter = 'converter'


class JobStatus(StrEnum):
    draft = 'draft'
    queued = 'queued'
    processing = 'processing'
    complete = 'complete'
    failed = 'failed'
    cancelled = 'cancelled'


class ServiceReportedStatus(StrEnum):
    """
    The only statuses a service may report. `draft`/`queued`/`cancelled` are
    gateway-owned; a service reporting them could make a running job re-submittable.

    """

    processing = 'processing'
    complete = 'complete'
    failed = 'failed'


class DatasetFormat(StrEnum):
    """
    Container/encoding. Orthogonal to DatasetRole — a DTM *is* a GeoTIFF.
    """

    geotiff = 'geotiff'
    cog = 'cog'
    las = 'las'
    laz = 'laz'
    geojson = 'geojson'
    pmtiles = 'pmtiles'
    field_3dtiles = '3dtiles'
    gltf = 'gltf'
    gml = 'gml'
    shp = 'shp'
    obj = 'obj'
    xyz = 'xyz'
    ply = 'ply'


class DatasetRole(StrEnum):
    """
    Semantic meaning, independent of container. Splitting this out is what makes the
    classify -> reconstruct pipeline expressible (see CONTRACT-CHANGES.md A1).

    """

    orthophoto = 'orthophoto'
    dem = 'dem'
    dtm = 'dtm'
    dsm = 'dsm'
    point_cloud = 'point_cloud'
    building_outline = 'building_outline'
    landcover = 'landcover'
    mesh = 'mesh'
    aoi = 'aoi'


class DatasetSource(StrEnum):
    uploaded = 'uploaded'
    generated = 'generated'


class DatasetStatus(StrEnum):
    processing = 'processing'
    ready = 'ready'
    failed = 'failed'


class UserRole(StrEnum):
    individual = 'individual'
    research = 'research'
    enterprise_admin = 'enterprise_admin'
    enterprise_member = 'enterprise_member'


class CreditTransactionType(StrEnum):
    job_debit = 'job_debit'
    job_refund = 'job_refund'
    topup = 'topup'
    grant = 'grant'


class NotificationType(StrEnum):
    job_complete = 'job_complete'
    job_failed = 'job_failed'
    dataset_ready = 'dataset_ready'
    dataset_failed = 'dataset_failed'
    credit_low = 'credit_low'
    system = 'system'


class ErrorCode(StrEnum):
    """
    Closed enum so clients branch on codes, never on human-readable messages.
    """

    validation_error = 'VALIDATION_ERROR'
    unauthenticated = 'UNAUTHENTICATED'
    forbidden = 'FORBIDDEN'
    not_found = 'NOT_FOUND'
    conflict = 'CONFLICT'
    insufficient_credits = 'INSUFFICIENT_CREDITS'
    storage_quota_exceeded = 'STORAGE_QUOTA_EXCEEDED'
    dataset_not_ready = 'DATASET_NOT_READY'
    dataset_in_use = 'DATASET_IN_USE'
    invalid_model_for_service = 'INVALID_MODEL_FOR_SERVICE'
    missing_required_input = 'MISSING_REQUIRED_INPUT'
    job_invalid_state_transition = 'JOB_INVALID_STATE_TRANSITION'
    job_not_deletable = 'JOB_NOT_DELETABLE'
    job_timeout = 'JOB_TIMEOUT'
    unsupported_conversion = 'UNSUPPORTED_CONVERSION'
    crs_mismatch = 'CRS_MISMATCH'
    rate_limited = 'RATE_LIMITED'
    internal_error = 'INTERNAL_ERROR'


class Meta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    request_id: str
    timestamp: Timestamp


class PageMeta(BaseModel):
    """
    Deliberately restates Meta's fields instead of allOf-extending it: Meta is
    closed (additionalProperties: false), and a closed schema cannot be extended
    via allOf in draft 2020-12 — the Meta arm would reject the pagination fields.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    request_id: str
    timestamp: Timestamp
    total: int = Field(..., ge=0)
    page: int = Field(..., ge=1)
    page_size: int = Field(..., ge=1)
    total_pages: int = Field(..., ge=0)


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: ErrorCode
    message: str
    details: dict[str, Any] | None


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Error
    meta: Meta


class Organization(BaseModel):
    """
    Every user belongs to exactly one organization. On register the gateway creates
    a personal org (`is_personal: true`) owned by that user, so `organization_id` is
    never null and org-scoping needs no special case for individuals.

    This replaces the PDF's free-text `User.organization` (CONTRACT-CHANGES C3):
    string equality would have leaked data between two companies both typing "Acme".

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    organization_id: UUID
    name: str = Field(..., max_length=200, min_length=1)
    is_personal: bool = Field(
        ...,
        description='Auto-created single-member org. Cannot be renamed or have members added.',
    )
    owner_id: UUID
    created_at: Timestamp
    updated_at: Timestamp


class User(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    email: EmailStr
    name: str = Field(..., max_length=200, min_length=1)
    organization_id: UUID = Field(
        ..., description='Never null — a personal org is created at registration.'
    )
    role: UserRole
    credits_remaining: int = Field(..., ge=0)
    storage_used_bytes: int = Field(..., ge=0)
    storage_quota_bytes: int = Field(..., ge=0)
    created_at: Timestamp
    updated_at: Timestamp


class Session(BaseModel):
    """
    `refresh_token` is deliberately NOT here. It is transported only as an
    HttpOnly; Secure; SameSite=Strict cookie (CONTRACT-CHANGES C1), so JS can
    never read it and XSS cannot exfiltrate it.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: UUID
    user_id: UUID
    access_token: str
    access_token_expires_at: Timestamp
    refresh_token_expires_at: Timestamp
    user_agent: str
    created_at: Timestamp


class Dataset(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dataset_id: UUID
    owner_id: UUID
    name: str = Field(..., max_length=255, min_length=1)
    dataset_format: DatasetFormat
    dataset_role: DatasetRole | None
    source: DatasetSource
    source_job_id: UUID | None = Field(
        ..., description='Non-null iff source == generated.'
    )
    source_service: ServiceName | None = Field(
        ..., description='Non-null iff source == generated.'
    )
    storage_key: str
    size_bytes: int = Field(..., ge=0)
    crs: Crs | None = Field(..., description='MUST be non-null once status == ready.')
    bbox: Bbox | None
    status: DatasetStatus
    error_code: ErrorCode | None
    error_message: str | None
    created_at: Timestamp
    updated_at: Timestamp


class DatasetDraft(BaseModel):
    """
    What a SERVICE returns in a callback — only what it can actually know.
    A service never sees the DB or the User table, so it cannot mint dataset_id,
    owner_id, or timestamps (CONTRACT-CHANGES A2). The GATEWAY mints identity:
    dataset_id, owner_id (from job.owner_id), source=generated, source_job_id,
    source_service, status, created_at, updated_at.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    dataset_format: DatasetFormat
    dataset_role: DatasetRole | None
    storage_key: str = Field(
        ..., description="MUST be under the job's `output_prefix`."
    )
    size_bytes: int = Field(..., ge=0)
    crs: Crs
    bbox: Bbox | None


class CreditTransaction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    transaction_id: UUID
    user_id: UUID
    job_id: UUID | None
    amount: int = Field(
        ..., description='Negative = debit, positive = credit. Credits are indivisible.'
    )
    type: CreditTransactionType
    balance_after: int = Field(..., ge=0)
    created_at: Timestamp


class Notification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    notification_id: UUID
    user_id: UUID
    job_id: UUID | None
    type: NotificationType
    message: str
    action_url: str | None = Field(
        ...,
        description='Deep link. Lets `system`/`credit_low` (which have no job_id) be actionable.',
    )
    read: bool
    created_at: Timestamp


class Model(StrEnum):
    cascade_building = 'cascade_building'
    geocarta = 'geocarta'


class OutputFormat(StrEnum):
    geojson = 'geojson'
    pmtiles = 'pmtiles'


class BuildingExtractionParams(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    model: Model
    output_formats: list[OutputFormat] = Field(..., min_length=1)
    output_crs: Crs | None = None


class BuildingExtractionInputs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aoi: UUID


class OutputFormatsGeneratedEnum(StrEnum):
    geojson = 'geojson'
    pmtiles = 'pmtiles'


class BuildingExtractionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    building_count: int = Field(..., ge=0)
    area_km2: float = Field(..., ge=0.0)
    confidence_avg_percent: float = Field(..., ge=0.0, le=100.0)
    output_formats_generated: list[OutputFormatsGeneratedEnum]


class Model1(StrEnum):
    csf = 'csf'
    dgcnn = 'dgcnn'


class OutputFormat1(StrEnum):
    las = 'las'
    laz = 'laz'
    field_3dtiles = '3dtiles'
    geotiff = 'geotiff'


class PointCloudClassificationParams(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    model: Model1
    output_formats: list[OutputFormat1] = Field(..., min_length=1)
    output_crs: Crs | None = None


class PointCloudClassificationInputs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    point_cloud: UUID


class PointsByClass(RootModel[int]):
    root: int = Field(..., ge=0)


class OutputFormatsGeneratedEnum1(StrEnum):
    las = 'las'
    laz = 'laz'
    field_3dtiles = '3dtiles'
    geotiff = 'geotiff'


class PointCloudClassificationResult(BaseModel):
    """
    A `geotiff` output from this service carries `dataset_role: dtm` or `dsm`, so its
    result can feed 3D Reconstruction's `elevation_source: dtm_dsm` path directly.
    This is the pipeline the PDF's single `dataset_type` enum made inexpressible
    (CONTRACT-CHANGES A1).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    points_total: int = Field(..., ge=0)
    points_by_class: dict[str, PointsByClass] = Field(
        ...,
        description="Keyed map, not a fixed struct: `csf` (a ground filter) and `dgcnn` (a learned\nclassifier) emit DIFFERENT class sets. Counts MUST sum to points_total.\nDiscover a model's classes at runtime via /capabilities rather than\nhardcoding keys in the UI.\n",
        examples=[{'ground': 120, 'vegetation': 80, 'building': 40, 'unclassified': 5}],
    )
    output_formats_generated: list[OutputFormatsGeneratedEnum1]


class OutputFormat2(StrEnum):
    geojson = 'geojson'
    pmtiles = 'pmtiles'


class LandcoverDetectionParams(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    model: Literal['pandala'] = Field(
        ..., description='Only one model — do NOT render as a choice in the UI.'
    )
    output_formats: list[OutputFormat2] = Field(..., min_length=1)
    output_crs: Crs | None = None


class LandcoverDetectionInputs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    orthophoto: UUID
    aoi: UUID = Field(
        ...,
        description="Always a dataset UUID. The PDF's `Dataset|geojson` union was the only union\namong the five services and was unreachable from the public API, which\naccepts only UUIDs (CONTRACT-CHANGES A6).\n",
    )


class Class(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    area_km2: float = Field(..., ge=0.0)
    percent: float = Field(..., ge=0.0, le=100.0)


class OutputFormatsGeneratedEnum2(StrEnum):
    geojson = 'geojson'
    pmtiles = 'pmtiles'


class LandcoverDetectionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    area_km2: float = Field(..., ge=0.0)
    classes: list[Class] = Field(
        ..., description='percent values MUST sum to 100 +/- 0.01.'
    )
    output_formats_generated: list[OutputFormatsGeneratedEnum2]


class Model2(StrEnum):
    dream3d = 'dream3d'
    cascade_mesh = 'cascade_mesh'


class ElevationSource(StrEnum):
    pointcloud = 'pointcloud'
    dtm_dsm = 'dtm_dsm'


class OutputFormat3(StrEnum):
    gltf = 'gltf'
    field_3dtiles = '3dtiles'


class Reconstruction3dParams(BaseModel):
    """
    elevation_source discriminates which inputs are required. The PDF stated this
    only in a comment, so generators emitted independent optionals and validated
    nothing — a mismatched job passed validation, debited credits, then died inside
    the worker (CONTRACT-CHANGES A5).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    model: Model2
    elevation_source: ElevationSource
    output_formats: list[OutputFormat3] = Field(..., min_length=1)
    output_crs: Crs | None = None


class Reconstruction3dInputs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    building_outline: UUID
    point_cloud: UUID | None = None
    dtm: UUID | None = None
    dsm: UUID | None = None
    remote_sensing: UUID | None = None


class OutputFormatsGeneratedEnum3(StrEnum):
    gltf = 'gltf'
    field_3dtiles = '3dtiles'


class Reconstruction3dResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mesh_triangle_count: int = Field(..., ge=0)
    buildings_reconstructed: int = Field(..., ge=0)
    output_formats_generated: list[OutputFormatsGeneratedEnum3]


class TargetFormat(StrEnum):
    field_3dtiles = '3dtiles'
    pmtiles = 'pmtiles'
    geojson = 'geojson'
    cog = 'cog'
    las = 'las'
    laz = 'laz'
    gltf = 'gltf'


class ConverterParams(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    target_format: TargetFormat
    output_crs: Crs | None = None


class ConverterInputs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input: UUID


class ConverterResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    output_format: DatasetFormat
    output_size_bytes: int = Field(..., ge=0)


class CreditsUsed(RootModel[int]):
    root: int = Field(
        ...,
        description='Reported by the service in the terminal callback. Null until terminal.',
        ge=0,
    )


class JobBase(BaseModel):
    job_id: UUID
    owner_id: UUID
    service: ServiceName
    status: JobStatus
    job_name: str = Field(..., max_length=255, min_length=1)
    output_dataset_ids: list[UUID]
    credits_estimated: int = Field(..., ge=0)
    credits_used: CreditsUsed | None = Field(
        ...,
        description='Reported by the service in the terminal callback. Null until terminal.',
    )
    progress_percent: int = Field(
        ...,
        description='Integer, not number (the PDF said `integer` on Job but `number` in the\ncallback; a Python 66.6667 would truncate or 500 the handler).\nMonotonic — the gateway drops backwards progress. status=complete implies 100.\n',
        ge=0,
        le=100,
    )
    error_code: ErrorCode | None
    error_message: str | None
    created_at: Timestamp
    started_at: Timestamp | None = Field(
        ...,
        description="Set by the GATEWAY when it receives the service's first processing callback.",
    )
    completed_at: Timestamp | None
    updated_at: Timestamp


class Service(StrEnum):
    building_extraction = 'building_extraction'
    pointcloud_classification = 'pointcloud_classification'
    landcover_detection = 'landcover_detection'
    reconstruction_3d = 'reconstruction_3d'
    converter = 'converter'


class Model3(StrEnum):
    cascade_building = 'cascade_building'
    geocarta = 'geocarta'


class BuildingExtractionJob(JobBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    service: Literal['building_extraction']
    model: Model3
    input_dataset_ids: BuildingExtractionInputs
    params: BuildingExtractionParams
    result_summary: BuildingExtractionResult | None


class Model4(StrEnum):
    csf = 'csf'
    dgcnn = 'dgcnn'


class PointCloudClassificationJob(JobBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    service: Literal['pointcloud_classification']
    model: Model4
    input_dataset_ids: PointCloudClassificationInputs
    params: PointCloudClassificationParams
    result_summary: PointCloudClassificationResult | None


class LandcoverDetectionJob(JobBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    service: Literal['landcover_detection']
    model: Literal['pandala']
    input_dataset_ids: LandcoverDetectionInputs
    params: LandcoverDetectionParams
    result_summary: LandcoverDetectionResult | None


class Model5(StrEnum):
    dream3d = 'dream3d'
    cascade_mesh = 'cascade_mesh'


class Reconstruction3dJob(JobBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    service: Literal['reconstruction_3d']
    model: Model5
    input_dataset_ids: Reconstruction3dInputs
    params: Reconstruction3dParams
    result_summary: Reconstruction3dResult | None


class ConverterJob(JobBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    service: Literal['converter']
    model: None = Field(
        ...,
        description='Converter has no model. The PDF made Job.model a required non-null\nstring while listing no models for converter, so every converter job\nhad to send a value that could not validate (CONTRACT-CHANGES A7).\n',
    )
    input_dataset_ids: ConverterInputs
    params: ConverterParams
    result_summary: ConverterResult | None


class Job(
    RootModel[
        BuildingExtractionJob
        | PointCloudClassificationJob
        | LandcoverDetectionJob
        | Reconstruction3dJob
        | ConverterJob
    ]
):
    root: (
        BuildingExtractionJob
        | PointCloudClassificationJob
        | LandcoverDetectionJob
        | Reconstruction3dJob
        | ConverterJob
    ) = Field(..., discriminator='service')


class CreditsUsed1(RootModel[int]):
    root: int = Field(
        ..., description='Actual consumption. Required when status is terminal.', ge=0
    )


class JobCallback(BaseModel):
    """
    Service -> Gateway. POST {gateway_internal_url}/v1/internal/jobs/{job_id}/callback
    Auth: Bearer <internal_service_token>. The gateway MUST reject a callback whose
    calling service does not match job.service.

    Delivery is AT-LEAST-ONCE with retries (1s,2s,4s,8s,16s,60s; max 10 attempts;
    retry on 5xx/timeout only, never 4xx). Services MUST persist unacknowledged
    terminal callbacks and resume retrying after their own restart.

    Gateway rules:
      - drop if sequence <= last processed sequence for this job (out-of-order/replay)
      - drop non-terminal callbacks once the job is terminal
      - a terminal callback for a `cancelled` job is ignored and its outputs GC'd
      - handling is idempotent on (job_id, sequence)

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    job_id: UUID
    sequence: int = Field(
        ...,
        description='Monotonic per job, assigned by the service. Enables replay/reorder rejection.',
        ge=0,
    )
    emitted_at: Timestamp
    status: ServiceReportedStatus
    progress_percent: int = Field(..., ge=0, le=100)
    output_datasets: list[DatasetDraft] = Field(
        ...,
        description='Empty unless status == complete. Drafts, not Datasets (see DatasetDraft).',
    )
    result_summary: (
        BuildingExtractionResult
        | PointCloudClassificationResult
        | LandcoverDetectionResult
        | Reconstruction3dResult
        | ConverterResult
        | None
    )
    credits_used: CreditsUsed1 | None = Field(
        ..., description='Actual consumption. Required when status is terminal.'
    )
    error_code: ErrorCode | None
    error_message: str | None


class JobCallbackAck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    received: Literal[True]


class RegisterRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: EmailStr
    password: str = Field(
        ...,
        description='Min 12 chars. Rejected against a common-password denylist.',
        max_length=256,
        min_length=12,
    )
    name: str = Field(..., max_length=200, min_length=1)
    organization_name: str | None = Field(
        None,
        description="Optional display name for the personal organization created alongside the\nuser. Defaults to the user's name. Does NOT join an existing organization —\nthat requires an invite.\n",
        max_length=200,
    )


class LoginRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: EmailStr
    password: str


class LogoutRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    all_devices: bool | None = False


class UpdateUserRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = Field(None, max_length=200, min_length=1)


class UpdateOrganizationRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=200, min_length=1)


class CreateUploadRequest(BaseModel):
    """
    Step 1 of the presigned direct-to-storage upload. The PDF's single multipart
    POST cannot carry the multi-GB LAS/LAZ files this platform exists to process
    (CONTRACT-CHANGES D7). size_bytes is checked against remaining quota BEFORE
    any URL is issued.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    dataset_format: DatasetFormat
    dataset_role: DatasetRole | None = None
    size_bytes: int = Field(..., ge=1)
    content_type: str | None = None


class Method(StrEnum):
    put = 'put'
    multipart = 'multipart'


class Url(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    part_number: int = Field(..., ge=1)
    url: str


class CreateUploadResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    upload_id: str
    method: Method
    part_size_bytes: int = Field(..., ge=1)
    urls: list[Url]
    expires_at: Timestamp


class Part(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    part_number: int = Field(..., ge=1)
    etag: str


class CompleteUploadRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    parts: list[Part] = Field(..., min_length=1)


class CreateJobRequestBase(BaseModel):
    job_name: str = Field(..., max_length=255, min_length=1)
    save_as_draft: bool | None = Field(
        True,
        description='false creates the job already queued AND debits credits immediately —\nit can therefore return 402, which the PDF documented only on /submit\n(CONTRACT-CHANGES M7).\n',
    )


class Model6(StrEnum):
    cascade_building = 'cascade_building'
    geocarta = 'geocarta'


class CreateBuildingExtractionJobRequest(CreateJobRequestBase):
    service: Literal['building_extraction']
    model: Model6
    job_name: str = Field(..., max_length=255, min_length=1)
    save_as_draft: bool | None = Field(
        None,
        description='false creates the job already queued AND debits credits immediately —\nit can therefore return 402, which the PDF documented only on /submit\n(CONTRACT-CHANGES M7).\n',
    )
    input_dataset_ids: BuildingExtractionInputs
    params: BuildingExtractionParams


class Model7(StrEnum):
    csf = 'csf'
    dgcnn = 'dgcnn'


class CreatePointCloudClassificationJobRequest(CreateJobRequestBase):
    service: Literal['pointcloud_classification']
    model: Model7
    job_name: str = Field(..., max_length=255, min_length=1)
    save_as_draft: bool | None = Field(
        None,
        description='false creates the job already queued AND debits credits immediately —\nit can therefore return 402, which the PDF documented only on /submit\n(CONTRACT-CHANGES M7).\n',
    )
    input_dataset_ids: PointCloudClassificationInputs
    params: PointCloudClassificationParams


class CreateLandcoverDetectionJobRequest(CreateJobRequestBase):
    service: Literal['landcover_detection']
    model: Literal['pandala']
    job_name: str = Field(..., max_length=255, min_length=1)
    save_as_draft: bool | None = Field(
        None,
        description='false creates the job already queued AND debits credits immediately —\nit can therefore return 402, which the PDF documented only on /submit\n(CONTRACT-CHANGES M7).\n',
    )
    input_dataset_ids: LandcoverDetectionInputs
    params: LandcoverDetectionParams


class Model8(StrEnum):
    dream3d = 'dream3d'
    cascade_mesh = 'cascade_mesh'


class CreateReconstruction3dJobRequest(CreateJobRequestBase):
    service: Literal['reconstruction_3d']
    model: Model8
    job_name: str = Field(..., max_length=255, min_length=1)
    save_as_draft: bool | None = Field(
        None,
        description='false creates the job already queued AND debits credits immediately —\nit can therefore return 402, which the PDF documented only on /submit\n(CONTRACT-CHANGES M7).\n',
    )
    input_dataset_ids: Reconstruction3dInputs
    params: Reconstruction3dParams


class CreateConverterJobRequest(CreateJobRequestBase):
    service: Literal['converter']
    model: None = Field(None)
    job_name: str = Field(..., max_length=255, min_length=1)
    save_as_draft: bool | None = Field(
        None,
        description='false creates the job already queued AND debits credits immediately —\nit can therefore return 402, which the PDF documented only on /submit\n(CONTRACT-CHANGES M7).\n',
    )
    input_dataset_ids: ConverterInputs
    params: ConverterParams


class LineItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str
    unit: str
    quantity: float
    unit_credits: float
    subtotal: int


class Breakdown(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    line_items: list[LineItem]
    total: int


class EstimateResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    credits_estimated: int = Field(..., ge=0)
    estimated_output_bytes: int = Field(..., ge=0)
    breakdown: Breakdown


class UsageSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    storage_used_bytes: int = Field(..., ge=0)
    storage_quota_bytes: int = Field(..., ge=0)
    credits_remaining: int = Field(..., ge=0)
    recent_transactions: list[CreditTransaction] = Field(
        ...,
        description='Last 10, newest first. Full history via GET /credits/transactions.',
        max_length=10,
    )


class ResolvedDataset(BaseModel):
    """
    What the gateway sends a service in place of a bare UUID: the dataset metadata
    plus a signed READ url. TTL MUST exceed max queue wait + max_job_duration, or a
    long-queued job dies on an expired URL (CONTRACT-CHANGES D15).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    dataset_id: UUID
    name: str
    dataset_format: DatasetFormat
    dataset_role: DatasetRole | None
    size_bytes: int = Field(..., ge=0)
    crs: Crs
    bbox: Bbox | None
    signed_url: str = Field(..., description='Treat as a credential. Never log.')
    signed_url_expires_at: Timestamp


class OutputUploadUrl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    output_format: DatasetFormat
    storage_key: str
    url: str
    expires_at: Timestamp


class InternalJobRequest(BaseModel):
    """
    Gateway -> Service. `input_datasets` maps the SAME keys as the job's
    input_dataset_ids, with UUIDs resolved to ResolvedDataset.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    job_id: UUID
    service: ServiceName
    model: str | None
    input_datasets: dict[str, ResolvedDataset]
    params: (
        BuildingExtractionParams
        | PointCloudClassificationParams
        | LandcoverDetectionParams
        | Reconstruction3dParams
        | ConverterParams
    )
    output_prefix: str = Field(
        ...,
        description='Storage prefix the service MUST write under. The PDF specified signed READ\nurls for inputs but never said how a service writes its OUTPUT bytes at all\n(CONTRACT-CHANGES A3).\n',
    )
    output_upload_urls: list[OutputUploadUrl] = Field(
        ..., description='Presigned PUT, one per requested output format.'
    )
    callback_url: str
    max_job_duration_seconds: int = Field(
        ...,
        description="After this, the gateway's reaper marks the job failed/JOB_TIMEOUT and\nrefunds. Without it a crashed worker strands a paid job forever\n(CONTRACT-CHANGES B4).\n",
        ge=1,
    )
    heartbeat_interval_seconds: int = Field(
        ...,
        description='The service MUST emit a processing callback at least this often while\nworking (see docs/job-lifecycle.md). Lets the reaper distinguish a slow\njob from a dead worker long before max_job_duration_seconds expires.\n',
        ge=1,
    )


class InternalJobAccepted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accepted: Literal[True]
    job_id: UUID
    credits_estimated: int = Field(..., ge=0)


class InternalJobStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    job_id: UUID
    status: ServiceReportedStatus
    progress_percent: int = Field(..., ge=0, le=100)


class InternalEstimateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_datasets: dict[str, ResolvedDataset]
    params: (
        BuildingExtractionParams
        | PointCloudClassificationParams
        | LandcoverDetectionParams
        | Reconstruction3dParams
        | ConverterParams
    )


class ServiceCapabilities(BaseModel):
    """
    Lets the gateway/UI discover what a service supports instead of hardcoding it.
    For the converter this carries the source->target conversion matrix, so the UI
    never offers an impossible conversion the user would be billed for.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    service: ServiceName
    version: str
    contract_version: str
    models: list[str]
    output_formats: list[DatasetFormat]
    max_input_size_bytes: int
    conversion_matrix: dict[str, list[DatasetFormat]] | None = Field(
        None,
        description='converter only. source dataset_format -> allowed target formats.',
    )


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    error = 'error'


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status
    detail: dict[str, Any] | None = None


class CreateJobRequest(
    RootModel[
        CreateBuildingExtractionJobRequest
        | CreatePointCloudClassificationJobRequest
        | CreateLandcoverDetectionJobRequest
        | CreateReconstruction3dJobRequest
        | CreateConverterJobRequest
    ]
):
    root: (
        CreateBuildingExtractionJobRequest
        | CreatePointCloudClassificationJobRequest
        | CreateLandcoverDetectionJobRequest
        | CreateReconstruction3dJobRequest
        | CreateConverterJobRequest
    ) = Field(
        ...,
        description='Discriminated on `service` so `params`, `model`, and `input_dataset_ids` are\nvalidated together. All referenced datasets MUST be status=ready at both create\nand submit (422 DATASET_NOT_READY otherwise) — a draft may be submitted days later.\n',
        discriminator='service',
    )
